import { MendixEntity, MendixPage, GeneratedFile } from '../types'

export function generateAppEntry(entities: MendixEntity[], pages: MendixPage[]): GeneratedFile {
  const userEntities = entities.filter(e => !e.isSystemEntity)
  const entityImports = userEntities.map(e =>
    `import ${e.name.toLowerCase()}Router from './routes/${e.name.toLowerCase()}'`
  ).join('\n')

  const pageImports = pages.slice(0, 30).map(p =>
    `import ${p.name}Router from './routes/${p.name}'`
  ).join('\n')

  const entityUses = userEntities.map(e =>
    `app.use('/api', ${e.name.toLowerCase()}Router)`
  ).join('\n')

  const pageUses = pages.slice(0, 30).map(p =>
    `app.use('/', ${p.name}Router)`
  ).join('\n')

  const content = `// Generated by mendix-to-node
// Express entry point — review before running in production
import express from 'express'
import path from 'path'
import bodyParser from 'body-parser'

// Entity (REST API) routes
${entityImports}

// Page routes
${pageImports}

const app = express()
const PORT = process.env.PORT || 3001

// Middleware
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

// View engine
app.set('view engine', 'ejs')
app.set('views', path.join(__dirname, '../views'))

// Routes — entity CRUD
${entityUses}

// Routes — pages
${pageUses}

// Home redirect
app.get('/', (req, res) => {
  res.redirect('/${pages[0]?.name.toLowerCase() || 'index'}')
})

app.listen(PORT, () => {
  console.log(\`Server running on http://localhost:\${PORT}\`)
})

export default app
`

  return {
    path: 'src/app.ts',
    content,
    category: 'config'
  }
}

export function generateDbSingleton(): GeneratedFile {
  return {
    path: 'src/db.ts',
    content: `// Generated by mendix-to-node
import { PrismaClient } from '@prisma/client'

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient }

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: ['query'],
  })

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
`,
    category: 'config'
  }
}
