import { GeneratedFile } from '../types'

export function generatePackageJson(projectName: string): GeneratedFile {
  const pkg = {
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: `Generated from Mendix project: ${projectName}`,
    main: 'dist/app.js',
    scripts: {
      build: 'tsc',
      start: 'node dist/app.js',
      dev: 'ts-node src/app.ts',
      'db:generate': 'prisma generate',
      'db:push': 'prisma db push',
      'db:migrate': 'prisma migrate dev'
    },
    dependencies: {
      express: '^4.18.2',
      ejs: '^3.1.9',
      'express-ejs-layouts': '^2.5.1',
      '@prisma/client': '^5.0.0',
      'body-parser': '^1.20.2',
      dotenv: '^16.3.1'
    },
    devDependencies: {
      typescript: '^5.0.0',
      'ts-node': '^10.9.1',
      prisma: '^5.0.0',
      '@types/express': '^4.17.17',
      '@types/ejs': '^3.1.2',
      '@types/node': '^20.0.0',
      '@types/express-ejs-layouts': '^2.5.4'
    }
  }

  return {
    path: 'package.json',
    content: JSON.stringify(pkg, null, 2) + '\n',
    category: 'config'
  }
}

export function generateTsConfig(): GeneratedFile {
  const config = {
    compilerOptions: {
      target: 'ES2020',
      module: 'commonjs',
      lib: ['ES2020'],
      outDir: './dist',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true
    },
    'ts-node': {
      transpileOnly: true
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist']
  }

  return {
    path: 'tsconfig.json',
    content: JSON.stringify(config, null, 2) + '\n',
    category: 'config'
  }
}

export function generateEnvExample(): GeneratedFile {
  return {
    path: '.env.example',
    content: `# Database connection (SQLite — no server needed)
DATABASE_URL=file:./dev.db

# Server port (optional, defaults to 3001)
PORT=3001
`,
    category: 'config'
  }
}

export function generateReadme(projectName: string, stats: { entityCount: number; microflowCount: number; pageCount: number }): GeneratedFile {
  return {
    path: 'README.md',
    content: `# ${projectName} — Generated Node.js App

> **Generated by [mendix-to-node](https://github.com/joshuamoesa/mendix-to-node)**
> This is a demo-quality starting point. Review all files before running in production.

## What Was Generated

- **${stats.entityCount} entities** → \`prisma/schema.prisma\` + \`src/types.ts\`
- **${stats.microflowCount} microflows** → \`src/services/*.ts\`
- **${stats.pageCount} pages** → \`views/*.ejs\` + \`src/routes/*.ts\`

## How to Run

\`\`\`bash
# Install dependencies
npm install

# Set up database
cp .env.example .env
# Edit .env with your DATABASE_URL

# Generate Prisma client and push schema
npm run db:generate
npm run db:push

# Start development server
npm run dev
\`\`\`

Open [http://localhost:3001](http://localhost:3001)

## What to Review Before Production

- [ ] \`prisma/schema.prisma\` — verify relations and field types
- [ ] \`src/services/*.ts\` — complex microflow logic is stubbed with \`// TODO\` comments
- [ ] \`src/routes/*.ts\` — add authentication and input validation
- [ ] \`views/*.ejs\` — add CSRF protection to forms
- [ ] Add error handling and logging
- [ ] Replace direct Prisma usage with a repository pattern

## Tech Stack

- **Express** — HTTP server
- **EJS** — server-side templates
- **Prisma** — database ORM
- **TypeScript** — type safety
`,
    category: 'config'
  }
}
