import { MendixEntity, MendixAttribute, GeneratedFile } from '../types'
import { pluralize } from '../utils/pageUtils'

function sanitizeFieldName(name: string): string {
  // Prisma field names cannot start with underscore
  return name.replace(/^_+/, '')
}

function attributeToField(attr: MendixAttribute): string {
  const fieldName = sanitizeFieldName(attr.name)

  if (attr.isAutoNumber) {
    return `  ${fieldName}  Int  @id @default(autoincrement())`
  }

  // SQLite does not support Decimal — map to Float
  const prismaType = attr.prismaType === 'Decimal' ? 'Float' : attr.prismaType
  const directives: string[] = []

  if (fieldName === 'id') {
    directives.push('@id')
  }

  return `  ${fieldName}  ${prismaType}${attr.isEnumeration ? ' // enum: ' + (attr.enumerationName || 'unknown') : ''}  ${directives.join(' ')}`
}

function entityToModel(entity: MendixEntity, relationLines: string[]): string {
  const lines: string[] = [`model ${entity.name} {`]

  // Add auto-incremented id if no auto-number attribute
  const hasAutoNumber = entity.attributes.some(a => a.isAutoNumber)
  if (!hasAutoNumber) {
    lines.push(`  id  Int  @id @default(autoincrement())`)
  }

  // Add attributes
  for (const attr of entity.attributes) {
    lines.push(attributeToField(attr))
  }

  // Append pre-computed relation fields (both forward and back-references)
  lines.push(...relationLines)

  lines.push(`}`)
  return lines.join('\n')
}

export function generatePrismaSchema(entities: MendixEntity[]): GeneratedFile {
  const userEntities = entities.filter(e => !e.isSystemEntity)

  // Pre-compute relation fields for every entity in a single pass.
  // For each M2M association owned by A → B, both sides are registered here:
  //   A gets: pluralize(B)  B[]   (forward)
  //   B gets: pluralize(A)  A[]   (back-reference)
  // Doing both sides together guarantees Prisma's implicit-M2M requirement is met.
  const relationFields = new Map<string, string[]>()
  const addRelation = (entityName: string, line: string) => {
    if (!relationFields.has(entityName)) relationFields.set(entityName, [])
    relationFields.get(entityName)!.push(line)
  }

  for (const entity of userEntities) {
    for (const assoc of entity.associations) {
      const targetName = assoc.targetEntityName
      if (assoc.type === 'many-to-many') {
        // Implicit M2M — both sides get a [] navigation field; Prisma creates the join table
        addRelation(entity.name, `  ${pluralize(targetName)}  ${targetName}[]`)
        addRelation(targetName,  `  ${pluralize(entity.name)}  ${entity.name}[]`)
      } else if (assoc.type === 'one-to-many') {
        // entity owns the FK (parent → child).
        // entity side: FK column + scalar navigation (nullable — entity may not reference target yet)
        // target side: array navigation (one target → many entities)
        const fkField = `${targetName.toLowerCase()}Id`
        addRelation(entity.name, `  ${fkField}  Int?`)
        addRelation(entity.name, `  ${targetName.toLowerCase()}  ${targetName}?  @relation(fields: [${fkField}], references: [id])`)
        addRelation(targetName,  `  ${pluralize(entity.name)}  ${entity.name}[]`)
      }
    }
  }

  const header = `// Generated by mendix-to-node
// Review before using in production

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
`

  const entityModels = userEntities.map(e => entityToModel(e, relationFields.get(e.name) ?? [])).join('\n\n')

  // Prisma requires at least one model to generate a client.
  // Add a placeholder when the project has no user entities.
  // Note: names starting with _ are reserved in Prisma 5 — do not use them.
  const placeholder = userEntities.length === 0
    ? `model AppConfig {\n  id    Int    @id @default(autoincrement())\n  key   String @unique\n  value String\n}\n`
    : ''

  const models = entityModels || placeholder

  return {
    path: 'prisma/schema.prisma',
    content: header + '\n' + models + '\n',
    category: 'data'
  }
}
