import { MendixEntity, MendixAttribute, GeneratedFile } from '../types'

function attributeToField(attr: MendixAttribute): string {
  if (attr.isAutoNumber) {
    return `  ${attr.name}  Int  @id @default(autoincrement())`
  }

  // SQLite does not support Decimal — map to Float
  const prismaType = attr.prismaType === 'Decimal' ? 'Float' : attr.prismaType
  const directives: string[] = []

  if (attr.name === 'id') {
    directives.push('@id')
  }

  return `  ${attr.name}  ${prismaType}${attr.isEnumeration ? ' // enum: ' + (attr.enumerationName || 'unknown') : ''}  ${directives.join(' ')}`
}

function entityToModel(entity: MendixEntity): string {
  const lines: string[] = [`model ${entity.name} {`]

  // Add auto-incremented id if no auto-number attribute
  const hasAutoNumber = entity.attributes.some(a => a.isAutoNumber)
  if (!hasAutoNumber) {
    lines.push(`  id  Int  @id @default(autoincrement())`)
  }

  // Add attributes
  for (const attr of entity.attributes) {
    lines.push(attributeToField(attr))
  }

  // Add relation fields for associations
  for (const assoc of entity.associations) {
    const targetModel = assoc.targetEntityName
    if (assoc.type === 'one-to-many' && assoc.owner === 'source') {
      // This entity "owns" the FK
      lines.push(`  ${assoc.name.toLowerCase()}s  ${targetModel}[]`)
    } else if (assoc.type === 'many-to-many') {
      lines.push(`  ${assoc.name.toLowerCase()}s  ${targetModel}[]`)
    }
  }

  lines.push(`}`)
  return lines.join('\n')
}

export function generatePrismaSchema(entities: MendixEntity[]): GeneratedFile {
  const userEntities = entities.filter(e => !e.isSystemEntity)

  const header = `// Generated by mendix-to-node
// Review before using in production

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
`

  const entityModels = userEntities.map(entityToModel).join('\n\n')

  // Prisma requires at least one model to generate a client.
  // Add a placeholder when the project has no user entities.
  // Note: names starting with _ are reserved in Prisma 5 — do not use them.
  const placeholder = userEntities.length === 0
    ? `model AppConfig {\n  id    Int    @id @default(autoincrement())\n  key   String @unique\n  value String\n}\n`
    : ''

  const models = entityModels || placeholder

  return {
    path: 'prisma/schema.prisma',
    content: header + '\n' + models + '\n',
    category: 'data'
  }
}
