import { MendixEntity, MendixAttribute, GeneratedFile } from '../types'

function attributeToProperty(attr: MendixAttribute): string {
  const optional = attr.isAutoNumber ? '?' : ''
  return `  ${attr.name}${optional}: ${attr.tsType}`
}

function entityToInterface(entity: MendixEntity): string {
  const lines: string[] = [`export interface ${entity.name} {`]

  if (!entity.attributes.some(a => a.isAutoNumber)) {
    lines.push(`  id?: number`)
  }

  for (const attr of entity.attributes) {
    lines.push(attributeToProperty(attr))
  }

  // Add relation type references
  for (const assoc of entity.associations) {
    if (assoc.type === 'one-to-many' && assoc.owner === 'source') {
      lines.push(`  ${assoc.name.toLowerCase()}s?: ${assoc.targetEntityName}[]`)
    } else if (assoc.type === 'many-to-many') {
      lines.push(`  ${assoc.name.toLowerCase()}s?: ${assoc.targetEntityName}[]`)
    }
  }

  lines.push(`}`)
  return lines.join('\n')
}

export function generateTypes(entities: MendixEntity[]): GeneratedFile {
  const userEntities = entities.filter(e => !e.isSystemEntity)

  const header = `// Generated by mendix-to-node
// TypeScript interfaces for all Mendix entities
`

  const interfaces = userEntities.map(entityToInterface).join('\n\n')

  return {
    path: 'src/types.ts',
    content: header + '\n' + interfaces + '\n',
    category: 'data'
  }
}
